### ISSUE TITLE
<Moto G Play>:<Android 6.0>:<After Adding Child, system does not give any message nor it navigates to Children list. instead it stays on the same page >

### ISSUE THREAD

**Issue by vinayagasundar** [ekstep/Integrated-Partner-App#8]
@RedmineQualitrix commented on [Thu Nov 23 2017](https://github.com/ekstep/IPA-TN/issues/10)

Steps to Reproduce:
1. Open the application.
2. Tap on "Add" button .
3. Provide all details .
4. Observe that after Adding Child, system does not give any message nor it navigates to Children list. instead it stays on the same page.

Expected Result:
Adding child should give a message and should navigate to children list.

Actual Result:
Adding Child, system does not give any message nor it navigates to Children list. instead it stays on the same page.

---

@RedmineQualitrix commented on [Fri Nov 24 2017](https://github.com/ekstep/IPA-TN/issues/10#issuecomment-346751798)

Working as Expected

**Comment by harshithaks** [comment]
@vinayagasundar why are these issues fixed but still open ? can this be tested and closed?
