### ISSUE TITLE
LFW : When language is changed is keeps on loading

### ISSUE THREAD

**Issue by joel-ekstep** [ekstep/Integrated-Partner-App#9]
@RedmineQualitrix commented on [Mon Feb 19 2018](https://github.com/ekstep/Genie/issues/1819)

Steps to Reproduce:
1. Open the LFW App v1.0.9.apk.
2. Create a Teacher Profile.
3. Tap on "Hamburger Menu".
4. Tap on "Settings".
5. Tap on "Language".
6. Change any Language and click on "Apply".
7. Observe that when language is changed is keeps on loading.

Expected Results:
On tapping "Apply" after language is selected we should get a successful message for language change.

Actual Results:
When language is changed is keeps on loading

[LFW Language change.zip](https://github.com/ekstep/Genie/files/1735730/LFW.Language.change.zip)

---

@joel-ekstep commented on [Mon Feb 19 2018](https://github.com/ekstep/Genie/issues/1819#issuecomment-366623287)

@RedmineQualitrix LFW app activity comes under Partner-App repository. Please move there.
Also, Vidyasagar is PM for Partner-App related bugs - please inform him regarding the same.

---

@RedmineQualitrix commented on [Mon Feb 19 2018](https://github.com/ekstep/Genie/issues/1819#issuecomment-366623976)

@Abhign  please move this issue to the above repo mentioned by Joel

---

@Abhign commented on [Mon Feb 19 2018](https://github.com/ekstep/Genie/issues/1819#issuecomment-366633005)

@joel-ekstep I don't have access to move the issue, Can you help me moving this issue to Partner-APP repo .

**Comment by RandhirGupta** [comment]
Moved the issue to IPA-LFW project. We are closing the issue here.
